# Schema for the configuration file of the Probe module.
probe.settings:
  type: config_object
  label: 'Probe settings'
  mapping:
    probe_key:
      label: 'Secret key'
      type: string
    probe_xmlrpc_ips:
      label: 'Allowed IP addresses for Probe XMLRPC calls'
      type: string
